spring:
  profiles:
    active : local
    group:
      local: db_local
      prod: db_prod
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    show-sql: false

  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always

logging:
  file:
    path : ./logs/
    max-size: 500MB
    max-history: 10
  level:
    root: info
    han.itemBox.aop: debug

--- # local
spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    activate:
      on-profile: local # ??????
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#      data-locations: classpath:sql/data-h2.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
#      schema-locations: classpath:sql/schema-h2.sql # 서버 시작시 ddl sql문을 실행할 위치 및 파일 지정
logging:
  file:
    path : log/
    max-size: 500MB
    max-history: 10
#  level:
#    root: info
#    test.testspring.aop: debug



server:
  port: 7080
  error:
    include-exception: true # ?? ??? exception? ??? ???? ??
    include-stacktrace: always # ?? ??? stacktrace ??? ??? ? ??

--- # prod
spring:
  jpa:
    hibernate:
      ddl-auto: none # ?? ?? ???
      dialect: org.hibernate.dialect.MariaDBDialect
  config:
    activate:
      on-profile: prod # ??????
server:
  port: 8080
  error:
    include-exception: true # ?? ??? exception? ??? ???? ??
    include-stacktrace: always # ?? ??? stacktrace ??? ??? ? ??

